[DADOS]
TIPO=1
IP=127.0.0.1
CAMINHO=C:\Progs5\AldistMotorTork
Senhabase=
GERAL=
TERMINALSERVER=
NInstancia=
DesativaSkin=SIM
IPZAP=192.168.1.115


[IMPRESSORA]
PEDIDO=c:\sef2\t.txt
NF=\\MAQJEFF\mp
CUPOMV=MP-2500 TH
CUPOMF=\\MAQJEFF\mp
OP1=\\MAQJEFF\mp
OP2=\\127.0.0.1\argox
COPIACUPOMV=1
COPIACUPOMRECIBO=1
LINHASALTOCUPOM=6
MODELO=0


[ALIQ]
T1=0700
T2=1200
T3=1700
T4=2500
T5=
T6=
T7=
T8=
T9=

[CUPOM]
PEDIDO=3611
LOJA=1
MODELO2=BEMATECH
MODELO1=BEMATH
MODELO=DARUMA

[TEF]
TEF=
TECBAN=
HIPER=
COPIA=2
N_IDENT=3831

[MENSAGEM]
BOLETO1=MENSAGEM 1 - 12345678901234567890123456789012345678901
BOLETO2=MENSAGEM 2 - 12345678901234567890123456789012345678901
BOLETO3=MENSAGEM 3 - 12345678901234567890123456789012345678901
BOLETO4=MENSAGEM 4 - 12345678901234567890123456789012345678901

[SINTEGRA]
ENTRADA=0
SAIDA=1
ECF=0
CONVENIO=2
NATUREZA=2
FINALIDADE=0
SEF=0
60D=0
60I=0
Competencia=Sim
Fazenda=0
CTe=0
60R=0
Local=C:\sef2\Sintegra_2021_08.txt
NFCeTerm=0

[SEF]
ENTRADA=0
SAIDA=0
ECF=0
Natureza=-1
Finalidade=-1
Local=C:\SEF2

[ETIQUETA]
MODELO=2
MODELOTERM=1
MODELOETQTERM=0
MODELODADOSTERM=-1
MODELOJATO=0
IMPCUSTO=0
MODELOMATRICIAL=-1
DADOSMATRICIAL=-1

[LOCALIZAR]
ITEM=0
ITEMCOMPRA=CODIGO
ITEMVENDA=CODIGO
PREI-ITEMVENDA=PREI_CODIGO
ITEMPREVENDA=PREI_CODIGO
ClienteContendo=S
ClienteInativo=N


[BALANCA]
MODELO=4
BAL_TAMANHOCODIGO=4
PORTACOM=
VELOCIDADE=
Tipo=Nenhum
Producao=0

[VENDA]
VENDARAPIDA=
TELATROCO=SIM
;DISPONIVEL / ATUAL
ESTOQUE=ATUAL
MensagemPedido=
;N o -> nao ir  mostrar no pedido que nao   valido com recibo

[ATUALIZAPRECO]
PRECOMEDIO=0
Fornecedor=0

[NFe]
Certificado=7C582109016CE614
XML=
Visualizar=S
Email=N
EmailBackup=jeffmc@zipmail.com.br
Transmitir=N
Certificado1=
ImportaCredST=N
Versao=310
SSLLib=4
CryptLib=3
HttpLib=2
XmlSignLib=4
SSLType=5
Frete=0

[Backup]
Driver=C: - Disco r gido
Pasta2=C:\sef2
Zip=V

[SPED]
Pis-Regime=2
Pis-Metodo=0
Pis-Tipo=0
Pis-Entrada=1
EFD-C170=0
EFD-Reducao=0
Pis-Saida=1
Pis-ECF=1
EFD-Local=C:\sef2
Pis-Caminho=C:\sef2
RegistroPAF=C:\SEF2
EFD-NFCe=0
EFD-Entrada=1
EFD-Saida=0
Pis-NFCe=1
EFD-CTe=0
EFD-BlocoK=0

[Coletor]
Delimitador=;    
SaltaLinha=N

[PosPrinter]
Modelo=1
Porta=RAW:PT380
PaginaDeCodigo=1
Impressora=Microsoft Print to PDF


[CONCILIADORA]
EMPRESA=023337044
IDEMPRESA=5634
SENHA=r$RdEWy7cM?ajNG9
LOJA=1

[CTe]
Certificado=7C582109016CE614
[CodBarra]
Temperatura=20
Marg_esquerda=0
